apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/created-by: workspaces
    app.kubernetes.io/part-of: workspaces
  name: alleditors-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workspace-editor-role 
subjects:
- kind: Group
  name: system:authenticated
