apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  namespace: system
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: workspaces-ingress-proxy
  rules:
  - host: api-workspaces.cluster.local # replace this with your current domain
    http:
      paths:
      - backend:
          service:
            name: rest-api-server
            port:
              number: 8080
        path: /healthz
        pathType: Exact
      - backend:
          service:
            name: rest-api-server
            port:
              number: 8080
        path: /apis/workspaces.io/v1alpha1/workspaces(/|$)(.+)
        pathType: ImplementationSpecific
      - backend:
          service:
            name: rest-api-server
            port:
              number: 8080
        path: /apis/workspaces.io/v1alpha1/namespaces/(.+)/workspaces
        pathType: ImplementationSpecific
