apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: workspaces-api
spec:
  rules:
  - host: api-workspaces.cluster.local # replace this with your current domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myapp
            port:
              number: 80
