apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: workspace-edit
spec:
  background: false
  validationFailureAction: Enforce
  rules:
    - name: update
      match:
        any:
        - resources:
            kinds:
            - workspaces.konflux.io/*/InternalWorkspace
            namespaces:
            - workspaces-system
            operations:
            - UPDATE
      validate:
        message: "Requestor ({{ request.userInfo.username }}) is not granted access as they are neither the owner nor the creator of workspace {{ request.object.metadata.name }}"
        deny:
          conditions:
            all:
            - key: '{{ request.oldObject.metadata.labels."internal.workspaces.konflux.io/owner" | to_string(@) }}'
              operator: NotEquals
              value: '{{ request.userInfo.username }}'
            - key: '{{ request.oldObject.metadata.labels."internal.workspaces.konflux.io/creator" | to_string(@) }}'
              operator: NotEquals
              value: '{{ request.userInfo.username }}'
            - key: >-
                {{
                  join('/', [
                    request.oldObject.metadata.labels."internal.workspaces.konflux.io/creator-namespace",
                    request.oldObject.metadata.labels."internal.workspaces.konflux.io/creator-serviceaccount"
                  ])
                }}
              operator: NotEquals
              value: "{{ join('/', [serviceAccountNamespace, serviceAccountName]) }}"
