apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service

spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: dashboard
  selector:
    app: ingress-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-proxy
spec:
  type: ClusterIP
  ports:
    - targetPort: web
      port: 8000
  selector:
    app: ingress-proxy
