apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  annotations:
    ingressclass.kubernetes.io/is-default-class: "false"
  name: workspaces-ingress-internal
spec:
  controller: traefik.io/ingress-controller
