apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../operator/config/default/

configMapGenerator:
  - name: e2e-test-cm
    options:
      disableNameSuffixHash: true
    literals:
      - WORKSPACE_QUOTA=3
  
replacements:
  - source:
      kind: ConfigMap
      name: e2e-test-cm
      fieldPath: data.WORKSPACE_QUOTA
      options:
        create: true
    targets:
      - options:
          create: false
        select:
          kind: ClusterPolicy
          group: kyverno.io
          name: workspace-quota
        fieldPaths:
          - 'spec.rules.[name=quota-same-user].context.[name=workspacesLimit].variable.value'
          - 'spec.rules.[name=quota-owner-change].context.[name=workspacesLimit].variable.value'
