http:
  services:
    kubesaw:
      loadBalancer:
        servers:
          - url: "http://api.toolchain-host-operator.svc.cluster.local:80"
    web:
      loadBalancer:
        servers:
        - url: "http://localhost:8080/"
  routers:
    app-apis:
      service: web
      entrypoints:
      - web
      rule: PathPrefix(`/apis/workspaces.konflux.io`) && ( Method(`GET`) || Method(`PUT`) )
      middlewares:
        - jwt-authorizer
      priority: 1
    app-healthz:
      service: web
      entrypoints:
      - web
      rule: Path(`/healthz`)
      priority: 20
    kubesaw:
      service: kubesaw
      entrypoints:
      - web
      rule: PathPrefix(`/`)
      priority: 5

# Middlewares
  middlewares:

# JWT Auth
    jwt-authorizer:
      plugin:
        jwt:
          required: true
          keys: []
          jwtHeaders:
            X-Subject: sub
